### ISSUE TITLE
Defaulting to EST instead of EDT, which then gives an error for the NFL Schedule hours for Kickoff

### ISSUE THREAD

**Issue by NadlesKVs** [boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool#1]
https://github.com/boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool/blob/66bd5a3c11e1cd59a892f8d9af628c049f75862f/script.js#L129C23-L129C23

**Comment by boilermaker-ben** [comment]
Excellent catch! I had another user experience an issue. I've removed that bit of the code and now have a timezone confirmation and prompt to change it if needed.

Apparently a timezone offset isn't needed, as I had been led to believe, if you have the script project set to the correct timezone through the settings menu as the ESPN API will respond with the correct game times based on your active timezone.
