### ISSUE TITLE
Formula in weekly sheet miscalculates percent correct with only Thursday picks and completed game

### ISSUE THREAD

**Issue by AustinOrphan** [boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool#13]
I have pulled my group's Thursday picks and gotten the results of the game, but the formula used resulted in 1600% for anyone who got the pick correct. This is because the formula checks if the pick matches the game's result. If the pick and the game result are blank, it counts it and adds it to the numerator
Anyway
I got this formula to work:
=iferror(if(and(counta($E$28:$T$28)>0,not(isblank($B3))),sum(filter(arrayformula(if($E3:$T3=$E$28:$T$28,1,0)),counta($E$28:$T$28)))-COUNTBLANK($E$28:$T$28)/counta($E$28:$T$28),),)
Haven't looked at updating the code for next week's sheet yet, but hopefully that won't be too bad

**Comment by AustinOrphan** [comment]
This may have been addressed since I generated the sheet, I haven't looked through all the changes yet, but I thought I was using the most recent version

**Comment by boilermaker-ben** [comment]
Austin, thanks for posting this! Good catch. I am going to update the "weeklySheet" code here and on the template file. I also found last night that the final row of previous data was not being restored if you recreate a sheet with pre-populated picks in it (thank goodness for Google Sheets revision history as a fallback).

Your solution seems to work, but the original intent that I had in the formula is represented here as the fix:

`=iferror(if(and(counta([outcome_range])>0,not(isblank([member_total_correct_cell]))),sum(filter(arrayformula(if([member_pick_range]=[outcome_range],1,0)),not(isblank([member_pick_range]))))/counta([outcome_range]),),)`
