### ISSUE TITLE
Picking Names on Form while unlocked

### ISSUE THREAD

**Issue by NadlesKVs** [boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool#2]
When the Member's are left unlocked and the form is generated, it has a drop down with names or you select "New User", fill out the rest of the form, and then it prompts to, "Section 2" to input a name.

When selecting a name already entered, the form defaulted to, "Continue to next section" which is "New User".

I resolved this by changing the result on the form to, "Submit Form" for any existing names.

![Screenshot 2023-09-05 142404](https://github.com/boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool/assets/21083131/a8f5bde3-936d-40ca-a906-2e161d00030b)

Change too "Submit Form"

I tried to find the appropriate line to adjust but wasn't able to locate it. I assume it is just defaulting to Continue to Next Section.

**Comment by boilermaker-ben** [comment]
I'm going to see what went wrong--are you doing pick 'ems only, survivor only, or both?

**Comment by NadlesKVs** [comment]
Everything minus Survivor.

**Comment by boilermaker-ben** [comment]
I believe I have it fixed now. Great catch. Thank you for pointing it out. 

The offending code was from a lingering situation where I was using a secondary page for comments, but later wrapped the comments into the bottom of the pick 'ems only page as I decided there was no clean way to display weekly comments in the survivor-pool-only approach. New code is pushed to GitHub and the Google Doc, if you want to re-import the entire block to your Google Script editor.
