### ISSUE TITLE
MNF pulling Saturday 

### ISSUE THREAD

**Issue by ChrisJMeng** [boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool#4]
![Screenshot 2023-09-11 092540](https://github.com/boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool/assets/144703001/63c691d3-3069-4d6d-a348-2f82abf63e4d)

It looks like the MNF info is pulling the S column instead of the T column for the MNF information.

**Comment by boilermaker-ben** [comment]
Looks like the comments are dropping into your "DIFFERENCE" column as well. How recently did you create the sheet, and what CONFIG values are you using? Survivor too?

**Comment by ChrisJMeng** [comment]
I have been messing with a new form, what exactly is the difference suppose to be pulling? I cant get it to load anything

**Comment by boilermaker-ben** [comment]
Difference is a calculated column of the absolute value between the TIEBREAKER actual (which will be placed in cell U2) and the tiebreaker values submitted by the users. Then the "WIN" column will calculate the winner based on the person with the most correct picks, using the absolute value (DIFFERENCE) column as the way it determines tiebreakers.
