### ISSUE TITLE
Error on creation

### ISSUE THREAD

**Issue by TwinkieSlamer** [boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool#7]
I keep getting this error during the initial setup.

Error	
SyntaxError: Unexpected token '<', "
	<!DOCTYPE "... is not valid JSON
fetchTeamsESPN	@ Code.gs:1054
fetchNFL	@ Code.gs:1069
runFirst	@ Code.gs:191

![image](https://github.com/boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool/assets/6481535/8224df74-e8e7-45d4-a2a5-cc6403ad3b48)

**Comment by boilermaker-ben** [comment]
Thanks for checking out the script and trying to get things set up. Currently the API endpoint for fetching the team schedule is unavailable and you won't be able to use this script until we get closer to the season--and hopefully at that time I'll be releasing a new version with some updates, but if for some reason the the API is no longer available from ESPN, then I'd need to rework quite a bit for fetching schedule and NFL data.
